project:
  type: website
  title: "NHSR Training"
  execute-dir: project

website:
  title: "NHSR-training"
  site-url: https://github.com/nhs-r-community/
  repo-url: https://github.com/nhs-r-community/NHSR-training
  issue-url: https://github.com/nhs-r-community/NHSR-training/issues/new/choose
  repo-actions: [edit, issue]
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
    right:
      - icon: github
        href: https://github.com/nhs-r-community/NHSR-training
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - intro-r-rstudio-summary.qmd
      - intro-git-rstudio-summary.qmd
      - shiny-summary.qmd
      - strategy-unit.qmd
      - other-courses.qmd
  page-navigation: true


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

callout-appearance: simple