# Shiny course

Originally written and delivered to the NHS-R Community, this one day course covers the basics of building a Shiny app.
Shiny has always been well known amongst R coders for "code first" dashboards that can be worked on in collaboration with others.
Whilst this course doesn't cover the use of Python in Shiny there it is now possible to use either language in Shiny.

The course will be run over two half days and is aimed at analysts who are familiar with R, perhaps having completed the Introduction to R and RStudio training through the NHS-R Community.

# Learning outcomes

- Understand the benefits and uses of Shiny.
- Create a basic Shiny app.

## Detailed Programme

The course is intended for analysts with little to no prior experience of Shiny and covers the following:

-   Introduction to Shiny and setting out your code
-   Your first application
-   Build a real application
-   Simplifying reactivity with reactive expressions

-   Optional:
    -   NSE in Shiny applications
    -   Bookmarks

-   Dynamic UI
-   Writing nice error messages for your Shiny applications
-   Downloading files/ Rmarkdown
-   Custom layout functions

-   {shinydashboard}
-   Interacting with a Shiny plot

## Prerequisites

The material is pitched at analysts with at least beginner level of R. 

# Duration
2 half days (3.5 hours each day)

# Course materials
[Materials](https://github.com/nhs-r-community/shiny-training#shiny-training-) are available through GitHub.